sudo: true

dist: trusty

language: c

before_install:
  - .travis/install-dependencies.sh 

script:
  - ./functional_tests/bionitio-test.sh -p bionitio -d functional_tests/test_data
  - .travis/unit-test.sh
